---
# vars file for nomad
nomad_zip: nomad_{{ nomad_version }}_linux_amd64.zip
nomad_url: "https://releases.hashicorp.com/nomad/{{ nomad_version }}/{{ nomad_zip }}"
nomad_dir: /usr/local/bin
nomad_path: "{{ nomad_dir }}/nomad"
nomad_config_dir: /etc/nomad.d
nomad_data_dir: /opt/nomad/data
nomad_profile_script: /etc/profile.d/nomad.sh
