---
# tasks file for common
- name: Set UTC timezone
  timezone: 
    name: Etc/UTC
  become: yes
  tags:
  - time

- name: Check for updates
  yum:
    list: updates
    update_cache: true
  when: ansible_facts['os_family'] == "RedHat"

- name: Install common base packages
  ansible.builtin.package:
    name: "{{ common_packages }}"
    state: present
    update_cache: yes

- name: Install OS specific packages
  vars:
     - target_os: "{{ ansible_facts['os_family']|lower }}"
  ansible.builtin.package:
    name: "{{ lookup('vars', target_os + '_packages') }}"
    state: present
    update_cache: yes

- name: Enable and start NTP service
  ansible.builtin.service:
    name: ntpd
    enabled: yes
    state: started
  when: ansible_facts['os_family'] == "RedHat"

- name: Enable and start Chrony service
  ansible.builtin.service:
    name: chrony
    enabled: yes
    state: started
  when: ansible_facts['os_family'] == "Debian"
