---
- name: Hashicorp-Labs base setup
  hosts: all
  become: yes
  roles:
    - common
  tags: [ common ]

- name: Vault installation
  hosts: all
  become: yes
  roles:
    - vault
  tags: [ vault ]

- name: Consul installation
  hosts: all
  become: yes
  roles:
    - consul
  tags: [ consul, envoy ]

- name: Nomad installation
  hosts: all
  become: yes
  roles:
    - nomad
  tags: [ nomad ]

- name: Docker installation
  hosts: all
  become: yes
  roles:
    - docker
  tags: [ docker ]

- name: Monitoring installation
  hosts: all
  become: yes
  roles:
    - monitoring
  tags: [ monitoring ]
