---
- name: Hashicorp-Labs base setup
  hosts: all
  become: yes
  roles:
    - common
  tags: [ common ]

- name: Vault installation
  hosts: all
  become: yes
  roles:
    - vault
  tags: [ vault ]

- name: Consul installation
  hosts: all
  become: yes
  roles:
    - consul
  tags: [ consul, envoy ]
