global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus_master'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: "faasd-gateway"
    scheme: http
    tls_config:
      insecure_skip_verify: true
    consul_sd_configs:
      - server: 'http://localhost:8500'
        services: ['faasd-mon']

  - job_name: 'nomad'
    scheme: http
    tls_config:
      insecure_skip_verify: true
    consul_sd_configs:
      - server: 'http://localhost:8500'
        services: ['nomad']

    relabel_configs:
      - source_labels: ['__meta_consul_tags']
        regex: '(.*)http(.*)'
        action: keep

    scrape_interval: 10s
    metrics_path: /v1/metrics
    params:
      format: ['prometheus']
  - job_name: 'nomad-client'
    scheme: http
    tls_config:
      insecure_skip_verify: true
    consul_sd_configs:
      - server: 'http://localhost:8500'
        services: ['nomad-client']

    relabel_configs:
      - source_labels: ['__meta_consul_tags']
        regex: '(.*)http(.*)'
        action: keep

    scrape_interval: 10s
    metrics_path: /v1/metrics
    params:
      format: ['prometheus']
