---
# vars file for common
common_packages:
  - ntp
  - git
  - wget
  - unzip
  - jq
  - dnsmasq
  - tcpdump
  - vim

debian_packages:
  - chrony
  - openjdk-8-jdk
  - dnsutils
  - netcat

redhat_packages:
  - bind-utils
  - java-1.8.0-openjdk
  - nc